{{{ include("templates/templates.inc.js") }}}


{{{ include("controllers/floorplan-unit-amenity-prop-detail-floorplans.js") }}}
{{{ include("controllers/floorplan-unit-amenity-prop-detail-floorplans-modal.js") }}}


{{{ include("controllers/floorplan-unit-amenity-prop-detail-upgrade-eligible-modal.js") }}}



{{{ include("directives/amenity-prop-detail-floorplans-actions.js") }}}


{{{ include("models/floorplans-tab-menu-config.js") }}}
{{{ include("models/floorplans-tab-menu.js") }}}
{{{ include("models/floorplans-amenity-added-list-config.js") }}}
{{{ include("models/floorplans-amenity-added.js") }}}


{{{ include("models/floorplans-upgrade-eligible-list-config.js") }}}
{{{ include("models/floorplans-upgrade-eligible.js") }}}




{{{ include("models/add-floorplan-list-manager.js") }}}
{{{ include("models/upgrade-eligible-list-manager.js") }}}






{{{ include("services/floorplans-amenity-added-floorplans-delete.js") }}}
{{{ include("services/floorplans-amenity-added-floorplans-get.js") }}}



