// External Modules

{{{ include("../../lib/angular/strap/js/scripts.js") }}}
{{{ include("../../lib/jquery/pnotify/js/scripts.js") }}}
{{{ include("../../lib/angular/pnotify/js/scripts.js") }}}

// RealPage Common

{{{ include("../../lib/realpage/common/js/scripts.js") }}}

// RealPage Modules

{{{ include("../../lib/realpage/actions-menu/js/scripts.js") }}}
{{{ include("../../lib/realpage/breadcrumbs/js/scripts.js") }}}
{{{ include("../../lib/realpage/busy-indicator/js/scripts.js") }}}
{{{ include("../../lib/realpage/date-range/js/scripts.js") }}}
{{{ include("../../lib/realpage/datepicker/js/scripts.js") }}}
{{{ include("../../lib/realpage/datetimepicker-v1/js/scripts.js") }}}
{{{ include("../../lib/realpage/float-scroll/js/scripts.js") }}}
{{{ include("../../lib/realpage/form-input-date/js/scripts.js") }}}
{{{ include("../../lib/realpage/form-input-text-v1/js/scripts.js") }}}
{{{ include("../../lib/realpage/form-select-menu-v1/js/scripts.js") }}}
{{{ include("../../lib/realpage/form-textarea-v1/js/scripts.js") }}}
{{{ include("../../lib/realpage/form-track-changes/js/scripts.js") }}}
{{{ include("../../lib/realpage/global-header/js/scripts.js") }}}
{{{ include("../../lib/realpage/grid-controls/js/scripts.js") }}}
{{{ include("../../lib/realpage/grid-pagination/js/scripts.js") }}}
{{{ include("../../lib/realpage/grid/js/scripts.js") }}}
{{{ include("../../lib/realpage/language/js/scripts.js") }}}
{{{ include("../../lib/realpage/page-title/js/scripts.js") }}}
{{{ include("../../lib/realpage/pagination/js/scripts.js") }}}
{{{ include("../../lib/realpage/scrolling-tabs-menu/js/scripts.js") }}}
{{{ include("../../lib/realpage/svg-icons/js/scripts.js") }}}
{{{ include("../../lib/realpage/tabs-menu/js/scripts.js") }}}
{{{ include("../../lib/realpage/toggle/js/scripts.js") }}}

// Unified Amenities Modules

{{{ include("base/_bundle.inc") }}}
{{{ include("config/_bundle.inc") }}}
{{{ include("controllers/_bundle.inc") }}}
{{{ include("models/_bundle.inc") }}}


{{{ //include('../../_common/primary-nav/js/_bundle.inc') }}}
