{{{ include("templates/templates.inc.js") }}}



{{{ include("controllers/amenity-prop-detail-assign-floorplans-modal.js") }}}
{{{ include("controllers/amenity-prop-detail-assign-upgrade-eligible-modal.js") }}}


{{{ include("models/amenity-added-aside.js") }}}
{{{ include("models/amenity-added-context.js") }}}

{{{ include("models/upgrade-eligible-aside.js") }}}
{{{ include("models/upgrade-eligible-context.js") }}}


{{{ include("models/upgrade-eligible-assign-floorplans.js") }}}
{{{ include("models/upgrade-eligible-assign-floorplans-config.js") }}}


{{{ include("models/amenity-added-assign-floorplans-config.js") }}}
{{{ include("models/amenity-added-assign-floorplans.js") }}}




