{{{ include("templates/templates.inc.js") }}}


{{{ include("controllers/amenity-prop-detail-units.js") }}}
{{{ include("controllers/amenity-prop-detail-units-upgrade-eligible-modal.js") }}}
{{{ include("controllers/amenity-prop-detail-units-confirm-modal.js") }}}


{{{ include("directives/amenity-prop-details-units-actions.js") }}}

{{{ include("models/units-tab-menu.js") }}}
{{{ include("models/units-tab-menu-config.js") }}}

{{{ include("models/units-amenity-added.js") }}}
{{{ include("models/units-amenity-added-config.js") }}}
{{{ include("models/units-upgrade-eligible.js") }}}
{{{ include("models/units-upgrade-eligible-list-manager.js") }}}
{{{ include("models/units-amenity-upgrade-eligible.js") }}}
{{{ include("models/units-upgrade-eligible-config.js") }}}


{{{ include("models/units-amenity-upgrade-eligible-config.js") }}}
{{{ include("models/add-units-list-manager.js") }}}


{{{ include("models/units-upgrade-eligible-action-config.js") }}}
{{{ include("models/units-amenity-added-action-config.js") }}}



{{{ include("services/units-amenity-added-get.js") }}}




