{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/amenities.js") }}}
{{{ include("controllers/amenities-delete.js") }}}

{{{ include("directives/amenity-actions.js") }}}

{{{ include("models/amenities-list-actions.js") }}}
{{{ include("models/amenities-list-config.js") }}}
{{{ include("models/amenities-list-item.js") }}}
{{{ include("models/assign-amenities-to-properties.js") }}}
{{{ include("models/amenities.js") }}}
{{{ include("models/select-amenity-data-manager.js") }}}


{{{ include("services/amenities-add.js") }}}
{{{ include("services/amenities-delete.js") }}}
{{{ include("services/amenities-get.js") }}}
{{{ include("services/amenities-update.js") }}}
{{{ include("services/select-amenities.js") }}}


