{{{ include("controllers/amenity-details.js") }}}

{{{ include("directives/amenity-detail-actions.js") }}}

{{{ include("models/amenity-data-manager.js") }}}
{{{ include("models/amenity-details-config.js") }}}
{{{ include("models/amenity-details.js") }}}
{{{ include("models/aside.js") }}}
{{{ include("models/context.js") }}}

{{{ include("services/amenities-get.js") }}}

{{{ include("templates/templates.inc.js") }}}

