angular.module('ui').run(['$templateCache', function ($templateCache) {
$templateCache.put("home/floorplan-unit/unit-assign/templates/assign-unit-upg-eli.html",
"<div class=\"rp-aside-modal rp-aside-modal-right rp-aside-modal-show rp-aside-modal-extend-modal-2\" ng-controller=\"FpuAmenityPropDetUpgEliAssignUnitsModalCtrl as fpaUpgEliUnitsAssignCtrl\"><div class=\"rp-aside-modal-header rp-aside-modal-header-wrap extend\" ng-if=\"fpaUpgEliUnitsAssignCtrl.isPageActive\"><a ng-click=\"fpaUpgEliUnitsAssignCtrl.closeAside()\"><i class=\"rp-aside-modal-close font-10\"></i></a><h2 class=\"rp-aside-modal-header-title\">Assign to Units</h2></div><div ng-if=\"fpaUpgEliUnitsAssignCtrl.isPageActive\" class=\"rp-aside-modal-content floorplan-amenity-assign-units-aside\"><div class=\"grid-controls\"><div class=\"grid-control-item\"><rp-toggle model=\"fpaUpgEliUnitsAssignCtrl.grid.filtersModel.state.active\" options=\"{\n" +
"                    defaultText: 'Filter',\n" +
"                    activeIconClass: 'rp-icon-filter',\n" +
"                    defaultIconClass: 'rp-icon-filter active'\n" +
"                }\"></rp-toggle></div></div><div class=\"assign-prop-grid\"><rp-grid model=\"fpaUpgEliUnitsAssignCtrl.grid\"></rp-grid><rp-grid-pagination model=\"fpaUpgEliUnitsAssignCtrl.gridPagination\"></rp-grid-pagination></div></div><div class=\"rp-aside-modal-footer rp-aside-modal-footer-btns aside-btns\"><button ng-click=\"fpaUpgEliUnitsAssignCtrl.closeAside()\" class=\"btn rounded btn-outline b-primary text-primary pad-left\">Cancel</button> <button ng-click=\"fpaUpgEliUnitsAssignCtrl.assign()\" class=\"btn rounded primary pad-left\">Update</button></div></div>");
$templateCache.put("home/floorplan-unit/unit-assign/templates/assign-unit.html",
"<div class=\"rp-aside-modal rp-aside-modal-right rp-aside-modal-show rp-aside-modal-extend-modal-2\" ng-controller=\"FpuAmenityPropDetAmeAddAssignUnitsModalCtrl as fpaAmeAddUnitsAssignCtrl\"><div class=\"rp-aside-modal-header rp-aside-modal-header-wrap extend\" ng-if=\"fpaAmeAddUnitsAssignCtrl.isPageActive\"><a ng-click=\"fpaAmeAddUnitsAssignCtrl.closeAside()\"><i class=\"rp-aside-modal-close font-10\"></i></a><h2 class=\"rp-aside-modal-header-title\">Assign to Units</h2></div><div ng-if=\"fpaAmeAddUnitsAssignCtrl.isPageActive\" class=\"rp-aside-modal-content floorplan-amenity-assign-units-aside\"><div class=\"grid-controls\"><div class=\"grid-control-item\"><rp-toggle model=\"fpaAmeAddUnitsAssignCtrl.grid.filtersModel.state.active\" options=\"{\n" +
"                    defaultText: 'Filter',\n" +
"                    activeIconClass: 'rp-icon-filter',\n" +
"                    defaultIconClass: 'rp-icon-filter active'\n" +
"                }\"></rp-toggle></div></div><div class=\"assign-prop-grid\"><rp-grid model=\"fpaAmeAddUnitsAssignCtrl.grid\"></rp-grid><rp-grid-pagination model=\"fpaAmeAddUnitsAssignCtrl.gridPagination\"></rp-grid-pagination></div></div><div class=\"rp-aside-modal-footer rp-aside-modal-footer-btns aside-btns\"><button ng-click=\"fpaAmeAddUnitsAssignCtrl.closeAside()\" class=\"btn rounded btn-outline b-primary text-primary pad-left\">Cancel</button> <button ng-click=\"fpaAmeAddUnitsAssignCtrl.assign()\" class=\"btn rounded primary pad-left\">Update</button></div></div>");
}]);
