{{{ include("templates/templates.inc.js") }}}



{{{ include("controllers/amenity-prop-detail-units-assign-unit-modal.js") }}}
{{{ include("controllers/amenity-prop-detail-upg-eli-units-assign-unit-modal.js") }}}


{{{ include("models/amenity-add-units.js") }}}
{{{ include("models/amenity-add-units-config.js") }}}


{{{ include("models/amenity-add-units-upg-eli.js") }}}
{{{ include("models/amenity-add-units-config-upg-eli.js") }}}

{{{ include("models/amenity-added-aside.js") }}}
{{{ include("models/upgrade-eligible.aside.js") }}}












