angular.module('ui').run(['$templateCache', function ($templateCache) {
$templateCache.put("home/floorplan-unit/floorplan-assign/templates/floorplan-assign.html",
"<div class=\"rp-aside-modal rp-aside-modal-right rp-aside-modal-show rp-aside-modal-extend-modal-2\" ng-controller=\"FpuAmenityPropDetAssignFloorPlansModalCtrl as fpaPropAssignCtrl\"><div class=\"rp-aside-modal-header rp-aside-modal-header-wrap extend\"><a ng-click=\"fpaPropAssignCtrl.closeAside()\"><i class=\"rp-aside-modal-close font-10\"></i></a><h2 class=\"rp-aside-modal-header-title\">Assign FloorPlans</h2></div><div ng-if=\"fpaPropAssignCtrl.isPageActive\" class=\"rp-aside-modal-content floorplan-amenity-assign-floorplan-aside\"><div class=\"grid-controls\"><div class=\"grid-control-item\"><rp-toggle model=\"fpaPropAssignCtrl.grid.filtersModel.state.active\" options=\"{\n" +
"                    defaultText: 'Filter',\n" +
"                    activeIconClass: 'rp-icon-filter',\n" +
"                    defaultIconClass: 'rp-icon-filter active'\n" +
"                }\"></rp-toggle></div></div><div class=\"assign-prop-grid\"><rp-grid model=\"fpaPropAssignCtrl.grid\"></rp-grid><rp-grid-pagination model=\"fpaPropAssignCtrl.gridPagination\"></rp-grid-pagination></div></div><div class=\"rp-aside-modal-footer rp-aside-modal-footer-btns aside-btns\"><button ng-click=\"fpaPropAssignCtrl.closeAside()\" class=\"btn rounded btn-outline b-primary text-primary pad-left\">Cancel</button> <button ng-click=\"fpaPropAssignCtrl.assign()\" class=\"btn rounded primary pad-left\">Assign</button></div></div>");
$templateCache.put("home/floorplan-unit/floorplan-assign/templates/upgrade-eligible-assign.html",
"<div class=\"rp-aside-modal rp-aside-modal-right rp-aside-modal-show rp-aside-modal-extend-modal-2\" ng-controller=\"FpuAmenityPropDetAssignUpgradeEligibleModalCtrl as fpaPropAssignUECtrl\"><div class=\"rp-aside-modal-header rp-aside-modal-header-wrap extend\"><a ng-click=\"fpaPropAssignUECtrl.closeAside()\"><i class=\"rp-aside-modal-close font-10\"></i></a><h2 class=\"rp-aside-modal-header-title\">Assign FloorPlans</h2></div><div class=\"rp-aside-modal-content floorplan-amenity-assign-floorplan-aside\"><div class=\"grid-controls\"><div class=\"grid-control-item\"><rp-toggle model=\"fpaPropAssignUECtrl.grid.filtersModel.state.active\" options=\"{\n" +
"                    defaultText: 'Filter',\n" +
"                    activeIconClass: 'rp-icon-filter',\n" +
"                    defaultIconClass: 'rp-icon-filter active'\n" +
"                }\"></rp-toggle></div></div><div class=\"assign-prop-grid\"><rp-grid model=\"fpaPropAssignUECtrl.grid\"></rp-grid><rp-grid-pagination model=\"fpaPropAssignUECtrl.gridPagination\"></rp-grid-pagination></div></div><div class=\"rp-aside-modal-footer rp-aside-modal-footer-btns aside-btns\"><button ng-click=\"fpaPropAssignUECtrl.closeAside()\" class=\"btn rounded btn-outline b-primary text-primary pad-left\">Cancel</button> <button ng-click=\"fpaPropAssignUECtrl.assign()\" class=\"btn rounded primary pad-left\">Assign</button></div></div>");
}]);
