//  Note: Please do not alter the order
//  in which files are being included

{{{ include("core-lazy-load.js") }}}
{{{ include("global-header.js") }}}
{{{ include("lazy-load.js") }}}
{{{ include("oc-lazyload.js") }}}
{{{ include("location.js") }}}
{{{ include("scope-annotations.js") }}}
{{{ include("breadcrumbs.js") }}}
{{{ // include("app-mock.js") }}}
{{{ include("resolve-modules.js") }}}
{{{ include("routes.js") }}}
{{{ // include("ga.js") }}}
{{{ include("global-nav.js") }}}
{{{ include("interceptor.js") }}}
