{{{ include("../../_base/js/_bundle.inc") }}}
{{{ include("../../amenities/js/_bundle.inc") }}}
{{{ include("../../properties/js/_bundle.inc") }}}
{{{ include("../../amenity-details/js/_bundle.inc") }}}
{{{ include("../../edit-amenity/js/_bundle.inc") }}}
{{{ include("../../amenity-property-details/js/_bundle.inc") }}}
{{{ include("../../assign-property/js/_bundle.inc") }}}
{{{ include("../../amenity-property-details-floorplans/js/_bundle.inc") }}}
{{{ include("../../amenity-property-details-units/js/_bundle.inc") }}}
{{{ include("../../amenity-property-details-pricepoints/js/_bundle.inc") }}}
{{{ include("../../amenity-price-point/js/_bundle.inc") }}}
{{{ include("../../floorplan-assign/js/_bundle.inc") }}}
{{{ include("../../unit-assign/js/_bundle.inc") }}}

