angular.module('ui').run(['$templateCache', function ($templateCache) {
$templateCache.put("home/floorplan-unit/amenity-property-details-units/templates/remove-amenityadd-unit.html",
"<div class=\"modal\"><div class=\"modal-dialog\"><div class=\"modal-content\"><div class=\"modal-header\"><h5 class=\"modal-title\">Delete Unit</h5></div><div class=\"modal-body p-lg\"><p>You are about to remove {{ctrl.model.units}} from the property’s list. It will no longer be listed for your property or available to assign to floor plans /units.</p></div><div class=\"modal-footer text-center\"><button type=\"button\" class=\"btn rounded neutral p-x-md\" ng-click=\"ctrl.hideConfirmModal()\">Cancel</button> <button type=\"button\" class=\"btn rounded primary p-x-md\" ng-click=\"ctrl.confirmDeleteSelectedUnits()\">Remove</button></div></div></div></div>");
$templateCache.put("home/floorplan-unit/amenity-property-details-units/templates/remove-upgrade-eligible-unit.html",
"<div class=\"modal\"><div class=\"modal-dialog\"><div class=\"modal-content\"><div class=\"modal-header\"><h5 class=\"modal-title\">remove Upgrade Eligible Unit</h5></div><div class=\"modal-body p-lg\"><p>You are about to remove {{ctrlUPgEli.model.units}} from the property’s list. It will no longer be listed for your property or available to assign to floor plans /units.</p></div><div class=\"modal-footer text-center\"><button type=\"button\" class=\"btn rounded neutral p-x-md\" ng-click=\"ctrlUPgEli.hideConfirmUpgEliModal()\">Cancel</button> <button type=\"button\" class=\"btn rounded primary p-x-md\" ng-click=\"ctrlUPgEli.confirmDeleteSelectedUpgEliUnits()\">Remove</button></div></div></div></div>");
$templateCache.put("home/floorplan-unit/amenity-property-details-units/templates/units-tab.html",
"<div class=\"floorplan-amenity-prop-details-units\" ng-controller=\"FpuAmenityPropDetUnitsCtrl as fpuAmePropDetUnits\"><div class=\"btn-tabs\"><rp-tabs-menu model=\"fpuAmePropDetUnits.tabsMenuModel.tabsMenu\"></rp-tabs-menu></div><div class=\"\" ng-if=\"fpuAmePropDetUnits.tabsMenuModel.tabsDataModel.unitsAmenityAdded.isActive\"><div class=\"amenity-tab\"><div class=\"rp-action-bar box\"><div rp-grid-model=\"fpuAmePropDetUnits.grid\" class=\"action-item rp-grid-select ft-form\"><label class=\"md-check dark-bluebox rp-grid-select-label\"><input type=\"checkbox\" ng-true-value=\"true\" ng-false-value=\"false\" class=\"rp-form-checkbox\" ng-model=\"gridSelect.model.selected\" ng-change=\"gridSelect.model.publishState()\"> <i class=\"primary\"></i></label><span class=\"rp-grid-select-icon rp-icon-angle-down\"></span></div><button class=\"action-item\" ng-click=\"fpuAmePropDetUnits.showDeleteFloorplanModal()\"><!-- <i class=\"action-icon rp-icon-trash\"></i> --> <span class=\"action-text\">Remove</span></button> <button class=\"action-item\" ng-click=\"fpuAmePropDetUnits.changePricePointModalBulk()\"><span class=\"action-text\">Change Price Point</span></button></div><div class=\"actions-row\"><div class=\"new-btn\"><button class=\"btn rounded primary\" ng-click=\"fpuAmePropDetUnits.assignAmeAddedUnit()\"><i class=\"fa fa-fw fa-plus icon-size\"></i> Assign Unit</button></div><div class=\"filters\"><div class=\"grid-controls\"><div class=\"grid-control-item\"><i class=\"icon rp-icon-printer\"></i> <span class=\"text\">Print</span></div><div class=\"grid-control-item\"><rp-toggle model=\"fpuAmePropDetUnits.grid.filtersModel.state.active\" options=\"{\n" +
"                                                        defaultText: 'Filter' ,\n" +
"                                                        defaultIconClass: 'rp-icon-filter active',\n" +
"                                                        activeIconClass: 'rp-icon-filter'\n" +
"                                                    }\"></rp-toggle></div></div></div></div><div class=\"ameneties-grid\"><rp-grid model=\"fpuAmePropDetUnits.grid\"></rp-grid><rp-grid-pagination model=\"fpuAmePropDetUnits.gridPagination\"></rp-grid-pagination></div></div></div><div class=\"tab-content\" ng-if=\"fpuAmePropDetUnits.tabsDataModel.unitsUpgradeEligible.isActive\"><div class=\"upgrade-eligible-tab\"><div class=\"rp-action-bar box\"><div rp-grid-model=\"fpuAmePropDetUnits.gridUpgElig\" class=\"action-item rp-grid-select ft-form\"><label class=\"md-check dark-bluebox rp-grid-select-label\"><input type=\"checkbox\" ng-true-value=\"true\" ng-false-value=\"false\" class=\"rp-form-checkbox\" ng-model=\"gridSelect.model.selected\" ng-change=\"gridSelect.model.publishState()\"> <i class=\"primary\"></i></label><span class=\"rp-grid-select-icon rp-icon-angle-down\"></span></div><button class=\"action-item\" ng-click=\"fpuAmePropDetUnits.showDeleteUpgradeEligibleModal()\"><!-- <i class=\"action-icon rp-icon-trash\"></i> --> <span class=\"action-text\">Remove</span></button></div><div class=\"actions-row\"><div class=\"new-btn\"><button class=\"btn rounded primary\" ng-click=\"fpuAmePropDetUnits.assignUpgEliUnit()\"><i class=\"fa fa-fw fa-plus icon-size\"></i> Assign Unit</button></div><div class=\"filters\"><div class=\"grid-controls\"><div class=\"grid-control-item\"><i class=\"icon rp-icon-printer\"></i> <span class=\"text\">Print</span></div><div class=\"grid-control-item\"><rp-toggle model=\"fpuAmePropDetUnits.gridUpgElig.filtersModel.state.active\" options=\"{\n" +
"                                                        defaultText: 'Filter' ,\n" +
"                                                        defaultIconClass: 'rp-icon-filter active',\n" +
"                                                        activeIconClass: 'rp-icon-filter'\n" +
"                                                    }\"></rp-toggle></div></div></div></div><div class=\"ameneties-grid\"><rp-grid model=\"fpuAmePropDetUnits.gridUpgElig\"></rp-grid><rp-grid-pagination model=\"fpuAmePropDetUnits.gridPaginationUpgElig\"></rp-grid-pagination></div></div></div></div>");
$templateCache.put("home/floorplan-unit/amenity-property-details-units/templates/upgrade-eligible-delete-template.html",
"<div fpu-amenity-prop-details-units-actions><a ng-click=\"amenityPropDetailsUnits.deleteUpgEliUnit(record)\"><i class=\"action-icon rp-icon-delete\"></i></a></div>");
}]);
