angular.module('ui').run(['$templateCache', function ($templateCache) {
$templateCache.put("home/floorplan-unit/amenity-property-details-floorplans/templates/amenity-added-delete-template.html",
"<div fpu-amenity-prop-details-flr-pln-actions><a ng-click=\"amenityPropDetailsFlrPlns.deleteAmeAddFlrPlan(record)\"><i class=\"action-icon rp-icon-delete\"></i></a></div>");
$templateCache.put("home/floorplan-unit/amenity-property-details-floorplans/templates/floorplans-tab.html",
"<div class=\"floorplan-amenity-prop-details-floorplans\" ng-controller=\"FpuAmenityPropDetFloorPlansCtrl as fpuAmePropDetFloorplans\"><div class=\"btn-tabs\"><rp-tabs-menu model=\"fpuAmePropDetFloorplans.tabsMenuModel.tabsMenu\"></rp-tabs-menu></div><div class=\"\" ng-if=\"fpuAmePropDetFloorplans.tabsMenuModel.tabsDataModel.floorPlanAmenityAdded.isActive\"><div class=\"amenity-tab\"><div class=\"rp-action-bar box\"><div rp-grid-model=\"fpuAmePropDetFloorplans.grid\" class=\"action-item rp-grid-select ft-form\"><label class=\"md-check dark-bluebox rp-grid-select-label\"><input type=\"checkbox\" ng-true-value=\"true\" ng-false-value=\"false\" class=\"rp-form-checkbox\" ng-model=\"gridSelect.model.selected\" ng-change=\"gridSelect.model.publishState()\"> <i class=\"primary\"></i></label><span class=\"rp-grid-select-icon rp-icon-angle-down\"></span></div><button class=\"action-item\" ng-click=\"fpuAmePropDetFloorplans.showDeleteFloorplanModal()\"><i class=\"action-icon rp-icon-trash\"></i> <span class=\"action-text\">Remove</span></button></div><div class=\"actions-row\"><div class=\"new-btn\"><button class=\"btn rounded primary\" ng-click=\"fpuAmePropDetFloorplans.assignFloorplan()\"><i class=\"fa fa-fw fa-plus icon-size\"></i> Assign Floor Plan</button></div><div class=\"filters\"><div class=\"grid-controls\"><div class=\"grid-control-item\"><i class=\"icon rp-icon-printer\"></i> <span class=\"text\">Print</span></div><div class=\"grid-control-item\"><rp-toggle model=\"fpuAmePropDetFloorplans.grid.filtersModel.state.active\" options=\"{\n" +
"                                                        defaultText: 'Filter' ,\n" +
"                                                        defaultIconClass: 'rp-icon-filter active',\n" +
"                                                        activeIconClass: 'rp-icon-filter'\n" +
"                                                    }\"></rp-toggle></div></div></div></div><div class=\"ameneties-grid\"><rp-grid model=\"fpuAmePropDetFloorplans.grid\"></rp-grid><rp-grid-pagination model=\"fpuAmePropDetFloorplans.gridPagination\"></rp-grid-pagination></div></div></div><div class=\"tab-content\" ng-if=\"fpuAmePropDetFloorplans.tabsDataModel.floorPlanUpgradeEligible.isActive\"><div class=\"upgrade-eligible-tab\"><div class=\"rp-action-bar box\"><div rp-grid-model=\"fpuAmePropDetFloorplans.gridUpgEli\" class=\"action-item rp-grid-select ft-form\"><label class=\"md-check dark-bluebox rp-grid-select-label\"><input type=\"checkbox\" ng-true-value=\"true\" ng-false-value=\"false\" class=\"rp-form-checkbox\" ng-model=\"gridSelect.model.selected\" ng-change=\"gridSelect.model.publishState()\"> <i class=\"primary\"></i></label><span class=\"rp-grid-select-icon rp-icon-angle-down\"></span></div><button class=\"action-item\" ng-click=\"fpuAmePropDetFloorplans.showDeleteUpgradeEligibleModal()\"><i class=\"action-icon rp-icon-trash\"></i> <span class=\"action-text\">Remove</span></button></div><div class=\"actions-row\"><div class=\"new-btn\"><button class=\"btn rounded primary\" ng-click=\"fpuAmePropDetFloorplans.assignUpgradeEligible()\"><i class=\"fa fa-fw fa-plus icon-size\"></i> Assign Floor Plan</button></div><div class=\"filters\"><div class=\"grid-controls\"><div class=\"grid-control-item\"><i class=\"icon rp-icon-printer\"></i> <span class=\"text\">Print</span></div><div class=\"grid-control-item\"><rp-toggle model=\"fpuAmePropDetFloorplans.gridUpgEli.filtersModel.state.active\" options=\"{\n" +
"                                                        defaultText: 'Filter' ,\n" +
"                                                        defaultIconClass: 'rp-icon-filter active',\n" +
"                                                        activeIconClass: 'rp-icon-filter'\n" +
"                                                    }\"></rp-toggle></div></div></div></div><div class=\"ameneties-grid\"><rp-grid model=\"fpuAmePropDetFloorplans.gridUpgEli\"></rp-grid><rp-grid-pagination model=\"fpuAmePropDetFloorplans.gridPaginationUpgEli\"></rp-grid-pagination></div></div></div></div>");
$templateCache.put("home/floorplan-unit/amenity-property-details-floorplans/templates/remove-floorplans-property.html",
"<div class=\"modal\"><div class=\"modal-dialog\"><div class=\"modal-content\"><div class=\"modal-header\"><h5 class=\"modal-title\">Delete Floorplan</h5></div><div class=\"modal-body p-lg\"><p>You are about to remove {{ctrl.model.floorPlanNames}} from the property’s list. It will no longer be listed for your property or available to assign to floor plans /units.</p></div><div class=\"modal-footer text-center\"><button type=\"button\" class=\"btn rounded neutral p-x-md\" ng-click=\"ctrl.hideModal()\">Cancel</button> <button type=\"button\" class=\"btn rounded primary p-x-md\" ng-click=\"ctrl.confirmDeleteSelectedFloorPlans()\">Remove</button></div></div></div></div>");
$templateCache.put("home/floorplan-unit/amenity-property-details-floorplans/templates/remove-upgrade-eligible-property.html",
"<div class=\"modal\"><div class=\"modal-dialog\"><div class=\"modal-content\"><div class=\"modal-header\"><h5 class=\"modal-title\">Delete Upgrade Eligible</h5></div><div class=\"modal-body p-lg\"><p>You are about to remove {{ctrlUE.model.floorPlanNames}} from the property’s list. It will no longer be listed for your property or available to assign to floor plans /units.</p></div><div class=\"modal-footer text-center\"><button type=\"button\" class=\"btn rounded neutral p-x-md\" ng-click=\"ctrlUE.hideModal()\">Cancel</button> <button type=\"button\" class=\"btn rounded primary p-x-md\" ng-click=\"ctrlUE.confirmDeleteSelectedAmenities()\">Remove</button></div></div></div></div>");
$templateCache.put("home/floorplan-unit/amenity-property-details-floorplans/templates/upgrade-eligible-delete-template.html",
"<div fpu-amenity-prop-details-flr-pln-actions><a ng-click=\"amenityPropDetailsFlrPlns.deleteUpgEliFlrPlan(record)\"><i class=\"action-icon rp-icon-delete\"></i></a></div>");
}]);
